- hosts: deploy1
  vars:
    - name:
  tasks:
    - name: delete
      file:
        path: /var/lib/docker/volumes/wordpress_wordpress_data/_data/wordpress/wp-content/themes/talon
        state: absent

    - name: copy
      copy:
        src: "{{name}}/talon"
        dest: /var/lib/docker/volumes/wordpress_wordpress_data/_data/wordpress/wp-content/themes/
        owner: misha
        group: daemon
        mode: '0775'
